### ISSUE TITLE
训练报错，IndexError: index out of range in self

### ISSUE THREAD

**Issue by Haitons** [easezyc/WSDM2022-PTUPCDR#9]
Traceback (most recent call last):
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/entry.py", line 55, in <module>
    Run(config).main()
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/run.py", line 242, in main
    self.TgtOnly(model, data_tgt, data_test, criterion, optimizer_tgt)
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/run.py", line 206, in TgtOnly
    self.train(data_tgt, model, criterion, optimizer, i, stage='train_tgt')
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/run.py", line 191, in train
    pred = model(X, stage)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/models.py", line 170, in forward
    x = self.tgt_model.forward(x)
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/models.py", line 60, in forward
    emb = self.embedding.forward(x)
  File "/Users/haiton/Documents/Projects/Autohome/Py_projects/github/WSDM2022-PTUPCDR/models.py", line 13, in forward
    uid_emb = self.uid_embedding(x[:, 0].unsqueeze(1))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 147, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/functional.py", line 1913, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

请问有遇到过这个问题吗

**Comment by Haitons** [comment]
看上去是uid和item_id的维度超了，但是我没有修改数据啊
